# Generated by Django 2.0.6 on 2020-04-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='auth_string',
            field=models.CharField(max_length=255),
        ),
    ]
