# Generated by Django 2.0.6 on 2020-04-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0004_studentclass'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentclass',
            table='student_class',
        ),
    ]
